## Basic Configuration
baseurl = "http://www.tczhong.com/"
languageCode = "en"
canonifyurls = "true"
theme = "hyde-hyde"
title = "TC blog"
## Hugo Built-in Features
disqusShortname = "tczhong"
googleAnalytics = ""
enableRobotsTXT = true

[author]
    name = "cczhong11"
    homepage = "https://cczhong11.github.io"

## Site Settings
[params]
    author = "Tc Zhong"
    title = "TC blog"
    description = "I am who I am. Love Cloud and Data science"
    authorimage = "https://avatars2.githubusercontent.com/u/7358252?s=460&v=4"
    dateformat = "Jan 1, 2006"
    highlightjs = true
    highlightjsstyle = "vs"
    paginate = 10
## Social Accounts
[params.social]
    github = "cczhong11"
    linkedin = "tianchen-zhong"
    email = "tczhong24@gmail.com"
    stackoverflow="7112540"
## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Project"
    identifier = "Project"
    weight = 301
    url = "/posts/project/index.html"  
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/hello"
[[menu.main]]
    name = "My Resume"
    identifier = "Resume"
    weight = 301
    url = "/tianchen_zhong.pdf"  
