## Basic Configuration
baseurl = "https://cczhong11.github.io/"
languageCode = "en"
canonifyurls = "true"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
    author = "Tc Zhong"
    title = "TC blog"
    description = "I am who I am. Love Cloud and Data science"
    authorimage = "/img/kirby.png"
    dateformat = "Jan 1, 2006"
    highlightjs = true
    highlightjsstyle = "vs"

## Social Accounts
[params.social]
    github = "cczhong11"
    linkedin = "tianchen-zhong"
    email = "tczhong24@gmail.com"
    
## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"

[[menu.main]]
    name = "My Resume"
    identifier = "Resume"
    weight = 301
    url = "/tianchen_zhong.pdf"   